
        package se.kth.clickr;
        import java.util.List;
        /*
        * This class was automatically generated by Floodway.
        */
        class Main{
            
public static class NoParams{}
public static class AboutResult{private long time;public void setTime(long time){this.time = time; }public long getTime(){ return this.time; }}
            
            
            public abstract static class AboutCallback{
                abstract void result(AboutResult result);
                abstract void err(String errorCode,String description);
            }
            
            public static Request about(NoParams params,final AboutCallback callback){
                return new Request("main","about",params,new Request.RequestCallback(AboutResult.class){
                    @Override
                    public void res(Object result){
                        callback.result((AboutResult) result);
                    }
                    @Override
                    public void err(String ec,String desc){
                        callback.err(ec,desc);
                    }
                });
            }
        
        }
    